/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.startProject.presentacion;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import mx.itson.startProject.entidades.Ruta;
import mx.itson.startProject.negocio.RutaNegocio;
import mx.itson.startProject.persistencia.RutaPersistencia;
import static mx.itson.startProject.presentacion.frmPeriodo.modelo;
import static mx.itson.startProject.presentacion.frmPeriodo.ruta;

/**
 *
 * @author Danielrodrigo
 */
public class frmRutas extends javax.swing.JFrame {

    static DefaultTableModel model;

    /**
     * Creates new form frmRutas
     */
    public frmRutas() {
        initComponents();
        tbRutas.setBackground(Color.white);
        tbRutas.setShowHorizontalLines(false);
        tbRutas.setShowVerticalLines(false);

        tbRutas.getColumnModel().getColumn(0).setMaxWidth(0);
        tbRutas.getColumnModel().getColumn(0).setMinWidth(0);
        tbRutas.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbRutas.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        cargarRutas();
    }

    public static void cargarRutas() {
        model = (DefaultTableModel) tbRutas.getModel();
        model.getDataVector().clear();
        RutaNegocio rn = new RutaNegocio();
        List<Ruta> rutas = new ArrayList<>();
        rutas = rn.verRutas();
        for (Ruta r : rutas) {
            if (!r.isEstado()) {
                model.addRow(new Object[]{
                    r.getId(),
                    r.getNombre(),
                    r.getDescripcion(),
                    r.getKilometraje()
                });
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRutas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSeleccionarRuta = new javax.swing.JButton();
        btnCancelarRuta = new javax.swing.JButton();
        txtBuscarRuta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(3, 169, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descrpción", "Kilometraje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRutas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbRutas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 580, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Ruta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 30));

        btnSeleccionarRuta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSeleccionarRuta.setText("Seleccionar");
        btnSeleccionarRuta.setBorder(null);
        btnSeleccionarRuta.setContentAreaFilled(false);
        btnSeleccionarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarRutaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 100, 30));

        btnCancelarRuta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelarRuta.setText("Cancelar");
        btnCancelarRuta.setBorder(null);
        btnCancelarRuta.setContentAreaFilled(false);
        btnCancelarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRutaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 100, 30));

        txtBuscarRuta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarRutaKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 200, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Rutas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_principal.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 100, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 100, 30));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 90, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_search_principal.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 340, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRutaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarRutaActionPerformed

    private void btnSeleccionarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarRutaActionPerformed
        int fila = tbRutas.getSelectedRow();
        model = (DefaultTableModel) tbRutas.getModel();
        if (fila != -1) {
            ruta.setId((int) model.getValueAt(fila, 0));
            ruta.setNombre((String) model.getValueAt(fila, 1));
            ruta.setDescripcion((String) model.getValueAt(fila, 2));
            ruta.setKilometraje((int) model.getValueAt(fila, 3));
            ruta.setEstado(true);
            RutaPersistencia rp = new RutaPersistencia();
            rp.editarRuta(ruta);
            modelo = (DefaultTableModel) frmPeriodo.tbRutas.getModel();
            modelo.addRow((new Object[]{
                ruta.getId(),
                ruta.getNombre()
            }));
            this.dispose();
        }
    }//GEN-LAST:event_btnSeleccionarRutaActionPerformed

    public void buscarRuta() throws SQLException {
        model = (DefaultTableModel) tbRutas.getModel();
        model.getDataVector().clear();
        List<Ruta> rutas = new ArrayList<>();
        RutaNegocio rn = new RutaNegocio();
        rutas = rn.verRutas();
        for (Ruta r : rutas) {
            if (r.getNombre().toLowerCase().matches(".*" + txtBuscarRuta.getText().toLowerCase() + ".*")) {
                model.addRow(new Object[]{
                    r.getId(),
                    r.getNombre(),
                    r.getDescripcion(),
                    r.getKilometraje()
                });
            } else {
                tbRutas.setVisible(false);
            }
        }
        tbRutas.setVisible(true);
    }
    private void txtBuscarRutaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarRutaKeyReleased
        try {
            buscarRuta();
        } catch (SQLException ex) {
            Logger.getLogger(frmRutas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarRutaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRutas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRuta;
    private javax.swing.JButton btnSeleccionarRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbRutas;
    private javax.swing.JTextField txtBuscarRuta;
    // End of variables declaration//GEN-END:variables
}
