/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.startProject.presentacion;

import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.startProject.entidades.Prestamo;
import mx.itson.startProject.entidades.Socio;
import mx.itson.startProject.persistencia.PrestamoPersistencia;
import mx.itson.startProject.persistencia.SocioPersistencia;
import static mx.itson.startProject.presentacion.PantallaPrincipal.socio;

/**
 *
 * @author Danielrodrigo
 */
public class frmSocios extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form frmSocios
     */
    public frmSocios() {
        initComponents();

        tbSocios.setBackground(Color.white);
        tbSocios.setShowHorizontalLines(false);
        tbSocios.setShowVerticalLines(false);

        tbSocios.getColumnModel().getColumn(0).setMaxWidth(0);
        tbSocios.getColumnModel().getColumn(0).setMinWidth(0);
        tbSocios.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbSocios.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        SocioPersistencia sp = new SocioPersistencia();
        cargarSocios();

    }

    public void cargarSocios() {
        SocioPersistencia sp = new SocioPersistencia();
        List<Socio> socios = new ArrayList<Socio>();
        socios = sp.obtenerTodos();
        model = (DefaultTableModel) tbSocios.getModel();
        model.getDataVector().clear();
        for (Socio s : socios) {
            if (!s.isEstado()) {
                model.addRow(new Object[]{
                    s.getId(),
                    s.getRfc(),
                    s.getNombre()
                });
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSocios = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnCacelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbCriterioSocio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtCriterioBusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(3, 169, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "RFC", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSocios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSocios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 580, 380));

        btnAceptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 100, 30));

        btnCacelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCacelar.setText("Cancelar");
        btnCacelar.setBorder(null);
        btnCacelar.setContentAreaFilled(false);
        btnCacelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCacelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCacelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 100, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, 30));

        cmbCriterioSocio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "RFC", "NOMBRE" }));
        cmbCriterioSocio.setBorder(null);
        cmbCriterioSocio.setOpaque(false);
        jPanel1.add(cmbCriterioSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 110, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Socios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 50));

        txtCriterioBusqueda.setBackground(new java.awt.Color(245, 246, 247));
        txtCriterioBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCriterioBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCriterioBusquedaActionPerformed(evt);
            }
        });
        txtCriterioBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCriterioBusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(txtCriterioBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 200, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_principal.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_search_principal.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 100, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 100, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        model = (DefaultTableModel) tbSocios.getModel();
        int fila = tbSocios.getSelectedRow();
        if (fila != -1) {
            socio = new Socio();
            socio.setId((int) model.getValueAt(fila, 0));
            socio.setRfc((String) model.getValueAt(fila, 1));
            socio.setNombre((String) model.getValueAt(fila, 2));
            if (PantallaPrincipal.indicador == 0) {
                Prestamo p = new Prestamo();
                PrestamoPersistencia pp = new PrestamoPersistencia();
                socio.setEstado(false);
                p = pp.obtenerPorSocio(socio.getId());
                if (p != null) {
                    JOptionPane.showMessageDialog(this, "Este socio ya tiene un préstamo activo");
                    socio = new Socio();
                } else {
                    PantallaPrincipal.lbSocio.setText(socio.getNombre());
                    PantallaPrincipal.indicador = -1;
                    this.dispose();
                }

            } else {
                socio.setEstado(true);
                DecimalFormat df = new DecimalFormat("00.00");
                frmPeriodo.lbSocio.setText(socio.getNombre());
                SocioPersistencia sp = new SocioPersistencia();
                sp.editarSocio(socio);
                PrestamoPersistencia pp = new PrestamoPersistencia();
                frmPeriodo.evaluarPrestamo(socio.getId());
                PantallaPrincipal.indicador = -1;
                this.dispose();
            }

        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún socio");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCacelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCacelarActionPerformed
        PantallaPrincipal.btnSeleccionarSocioPrestamo.setText("Seleccionar");
        socio = null;
        this.dispose();
    }//GEN-LAST:event_btnCacelarActionPerformed

    private void txtCriterioBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioBusquedaKeyReleased
        if (cmbCriterioSocio.getSelectedIndex() == 1) {
            buscarRfc();
        } else {
            if (cmbCriterioSocio.getSelectedIndex() == 2) {
                buscarNombre();
            }
        }
    }//GEN-LAST:event_txtCriterioBusquedaKeyReleased

    private void txtCriterioBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCriterioBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCriterioBusquedaActionPerformed

    public void buscarRfc() {
        model.getDataVector().clear();
        List<Socio> socios = new ArrayList<>();
        SocioPersistencia sp = new SocioPersistencia();
        socios = sp.obtenerTodos();
        for (Socio s : socios) {
            if (s.getRfc().toLowerCase().startsWith(txtCriterioBusqueda.getText().toLowerCase())) {
                model.addRow(new Object[]{
                    s.getId(), s.getRfc(), s.getNombre()
                });
            } else {
                tbSocios.setVisible(false);
            }
        }
        tbSocios.setVisible(true);
    }

    public void buscarNombre() {
        model = (DefaultTableModel) tbSocios.getModel();
        model.getDataVector().clear();
        List<Socio> socios = new ArrayList<>();
        SocioPersistencia sp = new SocioPersistencia();
        socios = sp.obtenerTodos();
        for (Socio s : socios) {
            if (s.getNombre().toLowerCase().matches(".*" + txtCriterioBusqueda.getText().toLowerCase() + ".*")) {
                model.addRow(new Object[]{
                    s.getId(), s.getNombre(), s.getRfc()
                });
            } else {
                tbSocios.setVisible(false);
            }
        }
        tbSocios.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSocios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCacelar;
    private javax.swing.JComboBox cmbCriterioSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSocios;
    private javax.swing.JTextField txtCriterioBusqueda;
    // End of variables declaration//GEN-END:variables
}
