/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.startProject.presentacion;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mx.itson.startProject.entidades.Periodo;
import mx.itson.startProject.entidades.Prestamo;
import mx.itson.startProject.entidades.Ruta;
import mx.itson.startProject.entidades.Socio;
import mx.itson.startProject.negocio.PeriodoNegocio;
import mx.itson.startProject.negocio.PrestamoNegocio;
import mx.itson.startProject.negocio.RutaNegocio;
import mx.itson.startProject.negocio.SocioNegocio;
import mx.itson.startProject.persistencia.Conexion;
import mx.itson.startProject.persistencia.PeriodoPersistencia;
import mx.itson.startProject.persistencia.PrestamoPersistencia;
import mx.itson.startProject.persistencia.SocioPersistencia;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Danielrodrigo
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    static DefaultTableModel model;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/Imagenes/prestamos_icon.png"));
        ImageIcon tamanio = new ImageIcon(imagen4.getImage().getScaledInstance(35, 35, 1));
        jTabbedPane1.setIconAt(3, tamanio);
        
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagenes/socios_icon.png"));
        ImageIcon tamanio1 = new ImageIcon(imagen3.getImage().getScaledInstance(35, 35, 1));
        jTabbedPane1.setIconAt(1, tamanio1);
        
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/ruta_icon.png"));
        ImageIcon tamanio2 = new ImageIcon(imagen2.getImage().getScaledInstance(35, 35, 1));
        jTabbedPane1.setIconAt(2, tamanio2);
        
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/Imagenes/periodos_icon.png"));
        ImageIcon tamanio3 = new ImageIcon(imagen1.getImage().getScaledInstance(35, 35, 1));
        jTabbedPane1.setIconAt(0, tamanio3);
        
        tbPeriodo.setBackground(Color.white);
        tbPeriodo.setShowHorizontalLines(false);
        tbPeriodo.setShowVerticalLines(false);
        
        this.setExtendedState(MAXIMIZED_BOTH);
        tbSocio.getColumnModel().getColumn(0).setMaxWidth(0);
        tbSocio.getColumnModel().getColumn(0).setMinWidth(0);
        tbSocio.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbSocio.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tbRuta.getColumnModel().getColumn(0).setMaxWidth(0);
        tbRuta.getColumnModel().getColumn(0).setMinWidth(0);
        tbRuta.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbRuta.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tbPrestamo.getColumnModel().getColumn(0).setMaxWidth(0);
        tbPrestamo.getColumnModel().getColumn(0).setMinWidth(0);
        tbPrestamo.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tbPrestamo.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tbPeriodo.getColumnModel().getColumn(0).setMaxWidth(0);
        tbPeriodo.getColumnModel().getColumn(0).setMinWidth(0);
        tbPeriodo.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tbPeriodo.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        rbTodosPeriodos.setSelected(true);
        SocioNegocio sn = new SocioNegocio();
        cargarSocios(sn.verSocios());
        RutaNegocio rn = new RutaNegocio();
        cargarRutas(rn.verRutas());
        PrestamoNegocio preN = new PrestamoNegocio();
        cargarPrestamos(preN.verPrestamos());
        PeriodoPersistencia pp = new PeriodoPersistencia();
        cargarPeriodos(pp.obtenerTodos());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        dcFechaInicioPeriodo = new com.toedter.calendar.JDateChooser();
        dcFechaFinPeriodo = new com.toedter.calendar.JDateChooser();
        btnCancelarPeriodo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnAgregarPeriodo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPeriodo = new javax.swing.JTable();
        btnCapturarPeriodo = new javax.swing.JButton();
        btnVerPeriodo = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        rbCapturadosReportes = new javax.swing.JRadioButton();
        rbPendientesReportes = new javax.swing.JRadioButton();
        rbTodosPeriodos = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnCerrarSesionPeriodo = new javax.swing.JButton();
        rbEspera = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreSocio = new javax.swing.JTextField();
        txtRfcSocio = new javax.swing.JTextField();
        btnGuardarSocio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSocio = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnEditarSocio = new javax.swing.JButton();
        btnCancelarSocio = new javax.swing.JButton();
        btnVerSocio = new javax.swing.JButton();
        cmbCriterioBusquedaSocio = new javax.swing.JComboBox();
        txtCriterioBusquedaSocio = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        btnCerrarSesionSocio = new javax.swing.JButton();
        btnCancelarBSocio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNombreRuta = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        btnAgregarRuta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbRuta = new javax.swing.JTable();
        btnEditarRuta = new javax.swing.JButton();
        btnCancelarRuta = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        txtBuscarRuta = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btnCerrarSesionRuta = new javax.swing.JButton();
        btnCancelarBRuta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dcFechaPrestamo = new com.toedter.calendar.JDateChooser();
        txtInteresPrestamo = new javax.swing.JTextField();
        cmbPlazoPrestamo = new javax.swing.JComboBox();
        txtCantidadPrestamo = new javax.swing.JTextField();
        btnSeleccionarSocioPrestamo = new javax.swing.JButton();
        btnGuardarPrestamo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPrestamo = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        lbDescuentoPrestamo = new javax.swing.JLabel();
        btnCalcularDescuento = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btnCancelarPrestamo = new javax.swing.JButton();
        btnVerPrestamo = new javax.swing.JButton();
        lbSocio = new javax.swing.JLabel();
        rbTodosPrestamos = new javax.swing.JRadioButton();
        rbActualesPrestamos = new javax.swing.JRadioButton();
        rbPasadosPrestamos = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtBuscarPrestamo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        btnCerrarSesionPrestamo = new javax.swing.JButton();
        btnCancelarBPrestamo = new javax.swing.JButton();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(245, 246, 247));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(3, 169, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Abrir período");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 40));

        dcFechaInicioPeriodo.setNextFocusableComponent(dcFechaFinPeriodo);
        jPanel4.add(dcFechaInicioPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, 30));
        jPanel4.add(dcFechaFinPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 30));

        btnCancelarPeriodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelarPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarPeriodo.setText("Cancelar");
        btnCancelarPeriodo.setToolTipText("Cancelar la apertura de periodo");
        btnCancelarPeriodo.setContentAreaFilled(false);
        btnCancelarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPeriodoActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelarPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 130, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Fecha de Inicio");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 30));

        btnAgregarPeriodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregarPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPeriodo.setText("Agregar");
        btnAgregarPeriodo.setToolTipText("Guardar la apertura del periodo");
        btnAgregarPeriodo.setContentAreaFilled(false);
        btnAgregarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeriodoActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregarPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 130, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Fecha Fin");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 30));

        tbPeriodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha de Inicio", "Fecha de Cierre", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPeriodo.setToolTipText("Lista de Periodos");
        tbPeriodo.setOpaque(false);
        tbPeriodo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPeriodo.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbPeriodo);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 830, 420));

        btnCapturarPeriodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCapturarPeriodo.setText("Capturar");
        btnCapturarPeriodo.setContentAreaFilled(false);
        btnCapturarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarPeriodoActionPerformed(evt);
            }
        });
        jPanel4.add(btnCapturarPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 130, 40));

        btnVerPeriodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerPeriodo.setText("Ver");
        btnVerPeriodo.setContentAreaFilled(false);
        btnVerPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPeriodoActionPerformed(evt);
            }
        });
        jPanel4.add(btnVerPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 130, 40));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Ver");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 50, 30));

        rbCapturadosReportes.setBackground(new java.awt.Color(3, 169, 244));
        buttonGroup1.add(rbCapturadosReportes);
        rbCapturadosReportes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbCapturadosReportes.setForeground(new java.awt.Color(255, 255, 255));
        rbCapturadosReportes.setText("Capturados");
        rbCapturadosReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCapturadosReportesActionPerformed(evt);
            }
        });
        jPanel4.add(rbCapturadosReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, -1, 30));

        rbPendientesReportes.setBackground(new java.awt.Color(3, 169, 244));
        buttonGroup1.add(rbPendientesReportes);
        rbPendientesReportes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbPendientesReportes.setForeground(new java.awt.Color(255, 255, 255));
        rbPendientesReportes.setText("Pendientes");
        rbPendientesReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPendientesReportesActionPerformed(evt);
            }
        });
        jPanel4.add(rbPendientesReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, 30));

        rbTodosPeriodos.setBackground(new java.awt.Color(3, 169, 244));
        buttonGroup1.add(rbTodosPeriodos);
        rbTodosPeriodos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbTodosPeriodos.setForeground(new java.awt.Color(255, 255, 255));
        rbTodosPeriodos.setText("Todos");
        rbTodosPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosPeriodosActionPerformed(evt);
            }
        });
        jPanel4.add(rbTodosPeriodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 80, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 130, 40));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 130, 40));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel4.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hey_1.png"))); // NOI18N
        jPanel4.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 140, 90));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel4.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 330, 450));

        btnCerrarSesionPeriodo.setText("Cerrar Sesion");
        btnCerrarSesionPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionPeriodoActionPerformed(evt);
            }
        });
        jPanel4.add(btnCerrarSesionPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, -1, -1));

        buttonGroup1.add(rbEspera);
        rbEspera.setText("En espera");
        rbEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEsperaActionPerformed(evt);
            }
        });
        jPanel4.add(rbEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, -1, -1));

        jTabbedPane1.addTab("Periodos", jPanel4);

        jPanel1.setBackground(new java.awt.Color(3, 169, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar socio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("RFC");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 30, 20));

        txtNombreSocio.setToolTipText("Ingresar el nombre del socio");
        txtNombreSocio.setNextFocusableComponent(txtRfcSocio);
        txtNombreSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreSocioKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 220, 30));

        txtRfcSocio.setToolTipText("Ingresar RFC del socio");
        txtRfcSocio.setNextFocusableComponent(txtCriterioBusquedaSocio);
        txtRfcSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRfcSocioKeyTyped(evt);
            }
        });
        jPanel1.add(txtRfcSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 220, 30));

        btnGuardarSocio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardarSocio.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarSocio.setText("Agregar");
        btnGuardarSocio.setToolTipText("Guardar datos del socio");
        btnGuardarSocio.setContentAreaFilled(false);
        btnGuardarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSocioActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 130, 40));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 0, 480));

        tbSocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "RFC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSocio.setToolTipText("Lista de Socios");
        tbSocio.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbSocio.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSocio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 800, 380));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar por");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 110, 30));

        btnEditarSocio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarSocio.setText("Editar");
        btnEditarSocio.setToolTipText("Modificar datos del Socio");
        btnEditarSocio.setContentAreaFilled(false);
        btnEditarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSocioActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 130, 30));

        btnCancelarSocio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelarSocio.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarSocio.setText("Cancelar");
        btnCancelarSocio.setToolTipText("Cancelar el registro del socio");
        btnCancelarSocio.setContentAreaFilled(false);
        btnCancelarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSocioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 130, 30));

        btnVerSocio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerSocio.setText("Ver");
        btnVerSocio.setToolTipText("Ver detalles de socio");
        btnVerSocio.setContentAreaFilled(false);
        btnVerSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSocioActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 120, 30));

        cmbCriterioBusquedaSocio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Nombre", "RFC" }));
        cmbCriterioBusquedaSocio.setToolTipText("Seleccione criterio de busqueda");
        jPanel1.add(cmbCriterioBusquedaSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, 30));

        txtCriterioBusquedaSocio.setToolTipText("Ingrese información a buscar");
        txtCriterioBusquedaSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCriterioBusquedaSocioKeyReleased(evt);
            }
        });
        jPanel1.add(txtCriterioBusquedaSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 200, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 130, 40));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 130, 50));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 450));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_search_principal.png"))); // NOI18N
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 130, 30));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 120, 30));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hey_1.png"))); // NOI18N
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 180, 90));

        btnCerrarSesionSocio.setText("Cerrar Sesion");
        btnCerrarSesionSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionSocioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesionSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, -1, -1));

        btnCancelarBSocio.setText("Cancelar Búsqueda");
        btnCancelarBSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBSocioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarBSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, -1, 30));

        jTabbedPane1.addTab("Socios", jPanel1);

        jPanel3.setBackground(new java.awt.Color(3, 169, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Agregar Ruta");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 340, 30));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Nombre");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 20));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Descripción");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Kilometraje");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        txtNombreRuta.setToolTipText("Ingresar el nombre de la ruta");
        txtNombreRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreRuta.setNextFocusableComponent(txtKilometraje);
        jPanel3.add(txtNombreRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 220, -1));

        txtKilometraje.setToolTipText("Ingresar los kilometros a recorrer en al ruta");
        txtKilometraje.setNextFocusableComponent(txtDescripcion);
        txtKilometraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKilometrajeKeyTyped(evt);
            }
        });
        jPanel3.add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 220, -1));

        btnAgregarRuta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregarRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarRuta.setText("Agregar");
        btnAgregarRuta.setToolTipText("Guardar datos de la ruta");
        btnAgregarRuta.setContentAreaFilled(false);
        btnAgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRutaActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 130, 50));

        tbRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descripción", "Kilometraje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRuta.setToolTipText("Lista de Rutas");
        tbRuta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbRuta.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbRuta);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 760, 420));

        btnEditarRuta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarRuta.setText("Editar");
        btnEditarRuta.setToolTipText("Modificar datos de la ruta");
        btnEditarRuta.setContentAreaFilled(false);
        btnEditarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRutaActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 140, 30));

        btnCancelarRuta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelarRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarRuta.setText("Cancelar");
        btnCancelarRuta.setToolTipText("Cancelar el registro de la ruta");
        btnCancelarRuta.setContentAreaFilled(false);
        btnCancelarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRutaActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 130, 30));

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setToolTipText("Ingresar la descripción de la ruta");
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setNextFocusableComponent(txtBuscarRuta);
        jScrollPane6.setViewportView(txtDescripcion);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 220, 130));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Buscar");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 110, 30));

        txtBuscarRuta.setToolTipText("Ingrese ruta a buscar");
        txtBuscarRuta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarRutaKeyReleased(evt);
            }
        });
        jPanel3.add(txtBuscarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 200, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_search_principal.png"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 130, 50));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, 470));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 140, 30));
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, 180, 110));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hey_1.png"))); // NOI18N
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 180, 90));

        btnCerrarSesionRuta.setText("Cerrar Sesion");
        btnCerrarSesionRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionRutaActionPerformed(evt);
            }
        });
        jPanel3.add(btnCerrarSesionRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 40, -1, -1));

        btnCancelarBRuta.setText("Cancelar Búsqueda");
        btnCancelarBRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBRutaActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelarBRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 73, 140, 30));

        jTabbedPane1.addTab("Rutas", jPanel3);

        jPanel2.setBackground(new java.awt.Color(3, 169, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar préstamo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 340, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Socio");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Cantidad");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 50, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Plazo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 40, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Interés");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 50, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Fecha");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, 20));

        dcFechaPrestamo.setNextFocusableComponent(cmbPlazoPrestamo);
        jPanel2.add(dcFechaPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 170, -1));

        txtInteresPrestamo.setToolTipText("Ingrese el interés que tendrá el préstamo");
        txtInteresPrestamo.setNextFocusableComponent(txtBuscarPrestamo);
        txtInteresPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresPrestamoKeyTyped(evt);
            }
        });
        jPanel2.add(txtInteresPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 170, 30));

        cmbPlazoPrestamo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "1 año", "2 años", "3 años", "4 años" }));
        cmbPlazoPrestamo.setToolTipText("Seleccione el plazo en años a pagar");
        jPanel2.add(cmbPlazoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 170, -1));

        txtCantidadPrestamo.setToolTipText("Ingresar la cantidad del préstamo");
        txtCantidadPrestamo.setNextFocusableComponent(dcFechaPrestamo);
        txtCantidadPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadPrestamoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCantidadPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, -1));

        btnSeleccionarSocioPrestamo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSeleccionarSocioPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarSocioPrestamo.setText("Seleccionar");
        btnSeleccionarSocioPrestamo.setToolTipText("Seleccionar un socio");
        btnSeleccionarSocioPrestamo.setContentAreaFilled(false);
        btnSeleccionarSocioPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarSocioPrestamoActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeleccionarSocioPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 20));

        btnGuardarPrestamo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPrestamo.setText("Agregar");
        btnGuardarPrestamo.setToolTipText("Guardar datos del préstamo");
        btnGuardarPrestamo.setContentAreaFilled(false);
        btnGuardarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPrestamoActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 130, 40));

        tbPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Socio", "Fecha", "Cantidad", "Interés", "Descuento Semanal", "Plazo", "Resto", "Total", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPrestamo.setToolTipText("Lista de prestamos");
        tbPrestamo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbPrestamo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPrestamo.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbPrestamo);
        if (tbPrestamo.getColumnModel().getColumnCount() > 0) {
            tbPrestamo.getColumnModel().getColumn(1).setMinWidth(200);
            tbPrestamo.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbPrestamo.getColumnModel().getColumn(5).setMinWidth(150);
            tbPrestamo.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 980, 410));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Descuento Semanal:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 120, 20));

        lbDescuentoPrestamo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbDescuentoPrestamo.setText("00.00");
        lbDescuentoPrestamo.setToolTipText("");
        jPanel2.add(lbDescuentoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 160, 20));

        btnCalcularDescuento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCalcularDescuento.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularDescuento.setText("Calcular totales");
        btnCalcularDescuento.setToolTipText("Calcular el descuento semanal y el monto total");
        btnCalcularDescuento.setContentAreaFilled(false);
        btnCalcularDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDescuentoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcularDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 130, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Total a Pagar:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 120, 20));

        lbTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTotal.setText("00.00");
        jPanel2.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 160, 20));

        btnCancelarPrestamo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarPrestamo.setText("Cancelar");
        btnCancelarPrestamo.setToolTipText("Cancelar el registro del prestamo");
        btnCancelarPrestamo.setContentAreaFilled(false);
        btnCancelarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPrestamoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 130, 40));

        btnVerPrestamo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerPrestamo.setText("Ver");
        btnVerPrestamo.setToolTipText("Ver detalles de préstamo");
        btnVerPrestamo.setContentAreaFilled(false);
        btnVerPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPrestamoActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 130, 30));

        lbSocio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbSocio.setText("Socio");
        jPanel2.add(lbSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 230, 20));

        rbTodosPrestamos.setBackground(new java.awt.Color(3, 169, 244));
        buttonGroup2.add(rbTodosPrestamos);
        rbTodosPrestamos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbTodosPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        rbTodosPrestamos.setText("Todos");
        rbTodosPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosPrestamosActionPerformed(evt);
            }
        });
        jPanel2.add(rbTodosPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, -1, -1));

        rbActualesPrestamos.setBackground(new java.awt.Color(3, 169, 244));
        buttonGroup2.add(rbActualesPrestamos);
        rbActualesPrestamos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbActualesPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        rbActualesPrestamos.setText("Actuales");
        rbActualesPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActualesPrestamosActionPerformed(evt);
            }
        });
        jPanel2.add(rbActualesPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, -1, -1));

        rbPasadosPrestamos.setBackground(new java.awt.Color(3, 169, 244));
        buttonGroup2.add(rbPasadosPrestamos);
        rbPasadosPrestamos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbPasadosPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        rbPasadosPrestamos.setText("Pasados");
        rbPasadosPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPasadosPrestamosActionPerformed(evt);
            }
        });
        jPanel2.add(rbPasadosPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ver");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 40, 30));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel24.setText("Buscar socio");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 120, 30));

        txtBuscarPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPrestamoKeyReleased(evt);
            }
        });
        jPanel2.add(txtBuscarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 190, 30));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 130, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 130, 40));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 140, 40));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_principal.png"))); // NOI18N
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 20));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 340, 490));

        jLabel31.setText("jLabel31");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_limit.png"))); // NOI18N
        jLabel36.setText("jLabel36");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 130, 30));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner_search_principal.png"))); // NOI18N
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 340, 30));
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 130, 50));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hey_1.png"))); // NOI18N
        jPanel2.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 180, 90));

        btnCerrarSesionPrestamo.setText("Cerrar Sesion");
        btnCerrarSesionPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionPrestamoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesionPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, -1, -1));

        btnCancelarBPrestamo.setText("Cancelar Búsqueda");
        btnCancelarBPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBPrestamoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarBPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        jTabbedPane1.addTab("Préstamo", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        tbPeriodo.clearSelection();
        tbPrestamo.clearSelection();
        tbRuta.clearSelection();
        tbSocio.clearSelection();
        rbTodosPeriodos.setSelected(true);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void txtCriterioBusquedaSocioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioBusquedaSocioKeyReleased
        if (cmbCriterioBusquedaSocio.getSelectedIndex() == 1) {
            buscarNombre();
        } else {
            if (cmbCriterioBusquedaSocio.getSelectedIndex() == 2) {
                buscarRfc();
            } else {
                txtCriterioBusquedaSocio.transferFocus();
                JOptionPane.showMessageDialog(this, "Seleccione un criterio de búsqueda");
            }
        }
    }//GEN-LAST:event_txtCriterioBusquedaSocioKeyReleased

    private void btnVerSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSocioActionPerformed
        int fila = tbSocio.getSelectedRow();
        if (fila != -1) {
            model = (DefaultTableModel) tbSocio.getModel();
            int idi = (int) model.getValueAt(fila, 0);
            URL in = this.getClass().getResource("/mx/itson/startProject/reportes/reporteSocio.jasper");
            JasperReport jr = null;
            JasperPrint jp = null;
            try {
                Map id = new HashMap();
                id.clear();
                id.put("id", idi);
                jr = (JasperReport) JRLoader.loadObject(in);
                jp = JasperFillManager.fillReport(jr, id, Conexion.conexion());
                if (jp.getPages().size() > 0) {
                    JasperViewer jv = new JasperViewer(jp, false);
                    jv.setVisible(true);
                    jv.setTitle("Reporte Socio");
                } else {
                    JOptionPane.showMessageDialog(this, "El socio no tiene historial de préstamo");
                }
                
            } catch (JRException jre) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, jre);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un socio de la lista");
        }
    }//GEN-LAST:event_btnVerSocioActionPerformed

    private void btnCancelarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSocioActionPerformed
        limpiarSocio();
    }//GEN-LAST:event_btnCancelarSocioActionPerformed

    private void btnEditarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSocioActionPerformed
        int fila = tbSocio.getSelectedRow();
        model = (DefaultTableModel) tbSocio.getModel();
        
        if (fila != -1) {
            Socio s = new Socio();
            s.setId((int) model.getValueAt(fila, 0));
            s.setRfc((String) model.getValueAt(fila, 2));
            s.setNombre((String) model.getValueAt(fila, 1));
            txtNombreSocio.setText(s.getNombre());
            txtRfcSocio.setText(s.getRfc());
            socio = s;
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un socio de la tabla");
        }
    }//GEN-LAST:event_btnEditarSocioActionPerformed

    private void btnGuardarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSocioActionPerformed
        if (verificarSocio()) {
            if (socio == null) {
                Socio s = new Socio();
                s.setRfc(txtRfcSocio.getText());
                s.setNombre(txtNombreSocio.getText());
                SocioNegocio sn = new SocioNegocio();
                sn.agregarSocio(s);
                limpiarSocio();
                cargarSocios(sn.verSocios());
            } else {
                socio.setRfc(txtRfcSocio.getText());
                socio.setNombre(txtNombreSocio.getText());
                SocioNegocio sn = new SocioNegocio();
                sn.editarSocio(socio);
                limpiarSocio();
                cargarSocios(sn.verSocios());
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        }
    }//GEN-LAST:event_btnGuardarSocioActionPerformed

    private void txtRfcSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcSocioKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isISOControl(c) && !Character.isLetterOrDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        if (Character.isLowerCase(c)) {
            String cad = ("" + c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
        if (txtRfcSocio.getText().length() == 12) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtRfcSocioKeyTyped

    private void txtNombreSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreSocioKeyTyped
        char c = evt.getKeyChar();
        soloLetras(c, evt, txtNombreSocio);
    }//GEN-LAST:event_txtNombreSocioKeyTyped

    private void txtBuscarRutaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarRutaKeyReleased
        try {
            buscarRuta();
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarRutaKeyReleased

    private void btnCancelarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRutaActionPerformed
        limpiarRuta();
    }//GEN-LAST:event_btnCancelarRutaActionPerformed

    private void btnEditarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRutaActionPerformed
        int fila = tbRuta.getSelectedRow();
        model = (DefaultTableModel) tbRuta.getModel();
        
        if (fila != -1) {
            Ruta r = new Ruta();
            r.setId((int) model.getValueAt(fila, 0));
            r.setNombre((String) model.getValueAt(fila, 1));
            r.setDescripcion((String) model.getValueAt(fila, 2));
            r.setKilometraje((int) model.getValueAt(fila, 3));
            txtNombreRuta.setText(r.getNombre());
            txtDescripcion.setText(r.getDescripcion());
            txtKilometraje.setText(String.valueOf(r.getKilometraje()));
            ruta = r;
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una ruta de la tabla");
        }
    }//GEN-LAST:event_btnEditarRutaActionPerformed

    private void btnAgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRutaActionPerformed
        if (verificarRuta()) {
            if (ruta == null) {
                Ruta r = new Ruta();
                r.setNombre(txtNombreRuta.getText());
                r.setDescripcion(txtDescripcion.getText());
                r.setKilometraje(Integer.parseInt(txtKilometraje.getText()));
                RutaNegocio rn = new RutaNegocio();
                rn.agregarRuta(r);
                limpiarRuta();
                cargarRutas(rn.verRutas());
            } else {
                ruta.setNombre(txtNombreRuta.getText());
                ruta.setDescripcion(txtDescripcion.getText());
                ruta.setKilometraje(Integer.parseInt(txtKilometraje.getText()));
                RutaNegocio rn = new RutaNegocio();
                rn.editarRuta(ruta);
                limpiarRuta();
                cargarRutas(rn.verRutas());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        }
    }//GEN-LAST:event_btnAgregarRutaActionPerformed

    private void txtKilometrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKilometrajeKeyTyped
        char c = evt.getKeyChar();
        soloNumeros(c, evt, txtKilometraje);
    }//GEN-LAST:event_txtKilometrajeKeyTyped

    private void txtBuscarPrestamoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPrestamoKeyReleased
        buscarSocioPrestamo();
    }//GEN-LAST:event_txtBuscarPrestamoKeyReleased

    private void rbTodosPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosPrestamosActionPerformed
        PrestamoPersistencia pp = new PrestamoPersistencia();
        cargarPrestamos(pp.obtenerTodos());
    }//GEN-LAST:event_rbTodosPrestamosActionPerformed

    private void btnVerPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPrestamoActionPerformed
        int fila = tbPrestamo.getSelectedRow();
        if (fila != -1) {
            model = (DefaultTableModel) tbPrestamo.getModel();
            int idi = (int) model.getValueAt(fila, 0);
            URL p = this.getClass().getResource("/mx/itson/startProject/reportes/reporteSocioAbonos.jasper");
            JasperReport jr = null;
            JasperPrint jp = null;
            try {
                Map id = new HashMap();
                id.clear();
                id.put("id", idi);
                jr = (JasperReport) JRLoader.loadObject(p);
                jp = JasperFillManager.fillReport(jr, id, Conexion.conexion());
                if (jp.getPages().size() > 0) {
                    JasperViewer jv = new JasperViewer(jp, false);
                    jv.setVisible(true);
                    jv.setTitle("Reporte de prestamos");
                } else {
                    JOptionPane.showMessageDialog(this, "El préstamo no ha tenido abonos");
                }
                
            } catch (JRException jre) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, jre);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un socio de la lista");
        }
    }//GEN-LAST:event_btnVerPrestamoActionPerformed

    private void btnCancelarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPrestamoActionPerformed
        limpiarPrestamo();
    }//GEN-LAST:event_btnCancelarPrestamoActionPerformed

    private void btnCalcularDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDescuentoActionPerformed
        if (verificarDescuento()) {
            calcularDescuento();
        } else {
            JOptionPane.showMessageDialog(btnCalcularDescuento, "Llene todos los campos anteriores");
        }
    }//GEN-LAST:event_btnCalcularDescuentoActionPerformed

    private void btnGuardarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPrestamoActionPerformed
        if (verificarPrestamo()) {
            Prestamo p = new Prestamo();
            p.setCantidad(Double.parseDouble(txtCantidadPrestamo.getText()));
            p.setSocio(socio);
            p.setInteres(Double.parseDouble(txtInteresPrestamo.getText()));
            p.setPlazo(cmbPlazoPrestamo.getSelectedIndex());
            p.setDescuento(Double.parseDouble(lbDescuentoPrestamo.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            p.setFecha(sdf.format(dcFechaPrestamo.getDate()));
            p.setEstado(true);
            p.setResto(Double.parseDouble(lbTotal.getText()));
            p.setTotal(Double.parseDouble(lbTotal.getText()));
            PrestamoNegocio prestN = new PrestamoNegocio();
            prestN.agregarPrestamo(p);
            limpiarPrestamo();
            socio = null;
            PrestamoNegocio preN = new PrestamoNegocio();
            cargarPrestamos(preN.verPrestamos());
        } else {
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        }
    }//GEN-LAST:event_btnGuardarPrestamoActionPerformed

    private void btnSeleccionarSocioPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarSocioPrestamoActionPerformed
        indicador = 0;
        lbSocio.setText("Socio");
        new frmSocios().setVisible(true);
    }//GEN-LAST:event_btnSeleccionarSocioPrestamoActionPerformed

    private void txtCantidadPrestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadPrestamoKeyTyped
        char c = evt.getKeyChar();
        soloNumeros(c, evt, txtCantidadPrestamo);
    }//GEN-LAST:event_txtCantidadPrestamoKeyTyped

    private void txtInteresPrestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresPrestamoKeyTyped
        char c = evt.getKeyChar();
        soloNumeros(c, evt, txtInteresPrestamo);
    }//GEN-LAST:event_txtInteresPrestamoKeyTyped

    private void rbTodosPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosPeriodosActionPerformed
        PeriodoPersistencia pp = new PeriodoPersistencia();
        cargarPeriodos(pp.obtenerTodos());
    }//GEN-LAST:event_rbTodosPeriodosActionPerformed

    private void rbPendientesReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPendientesReportesActionPerformed
        PeriodoPersistencia pp = new PeriodoPersistencia();
        cargarPeriodos(pp.obtenerPeriodosFiltrados("Pendiente"));
    }//GEN-LAST:event_rbPendientesReportesActionPerformed

    private void rbCapturadosReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCapturadosReportesActionPerformed
        PeriodoPersistencia pp = new PeriodoPersistencia();
        cargarPeriodos(pp.obtenerPeriodosFiltrados("Capturado"));
    }//GEN-LAST:event_rbCapturadosReportesActionPerformed
    

    private void btnVerPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPeriodoActionPerformed
        int fila = tbPeriodo.getSelectedRow();
        if (fila != -1) {
            model = (DefaultTableModel) tbPeriodo.getModel();
            int idi = (int) model.getValueAt(fila, 0);
            URL in = this.getClass().getResource("/mx/itson/startProject/reportes/reportePeriodo.jasper");
            JasperReport jr = null;
            JasperPrint jp = null;
            if (!"Pendiente".equals(model.getValueAt(fila, 3)) && !"En espera".equals(model.getValueAt(fila, 3))) {
                try {
                    Map id = new HashMap();
                    id.clear();
                    id.put("id", idi);
                    jr = (JasperReport) JRLoader.loadObject(in);
                    jp = JasperFillManager.fillReport(jr, id, Conexion.conexion());
                    JasperViewer jv = new JasperViewer(jp, false);
                    jv.setVisible(true);
                    jv.setTitle("Reporte periodo");
                    
                } catch (JRException jre) {
                    Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, jre);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El periodo aún no ha sido capturado");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un periodo de la lista");
        }
    }//GEN-LAST:event_btnVerPeriodoActionPerformed
    
    public void cargarReportePeriodo(int idPeriodo) {
        URL in = this.getClass().getResource("/mx/itson/startProject/reportes/reportePeriodo.jasper");
        JasperReport jr = null;
        JasperPrint jp = null;
        try {
            Map id = new HashMap();
            id.clear();
            id.put("id", idPeriodo);
            jr = (JasperReport) JRLoader.loadObject(in);
            jp = JasperFillManager.fillReport(jr, id, Conexion.conexion());
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.setTitle("Reporte periodo");
            
        } catch (JRException jre) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, jre);
        }
        
    }

    private void btnCapturarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarPeriodoActionPerformed
        int fila = tbPeriodo.getSelectedRow();
        model = (DefaultTableModel) tbPeriodo.getModel();
        if (fila != -1) {
            periodo = new Periodo();
            periodo.setId((int) model.getValueAt(fila, 0));
            periodo.setFechaInicio((String) model.getValueAt(fila, 1));
            periodo.setFechaFin((String) model.getValueAt(fila, 2));
            periodo.setEstado((String) model.getValueAt(fila, 3));
            periodo.setTotal(0);
            if (periodo.getEstado().equals("Capturado")) {
                int rps = JOptionPane.showConfirmDialog(this, "El periodo ya ha sido capturado, ¿desea ver el reporte?");
                if (rps == 0) {
                    cargarReportePeriodo(periodo.getId());
                }
            } else {
                frmPeriodo frperiodo = new frmPeriodo();
                frperiodo.setVisible(true);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un periodo en la tabla");
        }
    }//GEN-LAST:event_btnCapturarPeriodoActionPerformed

    private void btnCancelarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPeriodoActionPerformed
        dcFechaInicioPeriodo.setDate(null);
        dcFechaFinPeriodo.setDate(null);
    }//GEN-LAST:event_btnCancelarPeriodoActionPerformed

    private void btnAgregarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeriodoActionPerformed
        if (verificarPeriodo()) {
            Periodo p = new Periodo();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            p.setFechaInicio(sdf.format(dcFechaInicioPeriodo.getDate()));
            p.setFechaFin(sdf.format(dcFechaFinPeriodo.getDate()));
            p.setEstado("Pendiente");
            PeriodoNegocio pn = new PeriodoNegocio();
            pn.agregarPeriodo(p);
            dcFechaInicioPeriodo.setDate(null);
            dcFechaFinPeriodo.setDate(null);
            PeriodoPersistencia pp = new PeriodoPersistencia();
            cargarPeriodos(pp.obtenerTodos());
            
        } else {
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        }
    }//GEN-LAST:event_btnAgregarPeriodoActionPerformed

    private void btnCerrarSesionPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionPeriodoActionPerformed
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionPeriodoActionPerformed

    private void btnCerrarSesionSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionSocioActionPerformed
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionSocioActionPerformed

    private void btnCerrarSesionRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionRutaActionPerformed
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionRutaActionPerformed

    private void btnCerrarSesionPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionPrestamoActionPerformed
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionPrestamoActionPerformed

    private void rbActualesPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActualesPrestamosActionPerformed
        PrestamoPersistencia pp = new PrestamoPersistencia();
        cargarPrestamos(pp.obtenerFiltrados(true));
    }//GEN-LAST:event_rbActualesPrestamosActionPerformed

    private void rbPasadosPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPasadosPrestamosActionPerformed
        PrestamoPersistencia pp = new PrestamoPersistencia();
        cargarPrestamos(pp.obtenerFiltrados(false));
    }//GEN-LAST:event_rbPasadosPrestamosActionPerformed

    private void rbEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEsperaActionPerformed
        PeriodoPersistencia pp = new PeriodoPersistencia();
        cargarPeriodos(pp.obtenerPeriodosFiltrados("En espera"));
    }//GEN-LAST:event_rbEsperaActionPerformed

    private void btnCancelarBSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBSocioActionPerformed
        cmbCriterioBusquedaSocio.setSelectedIndex(0);
        txtCriterioBusquedaSocio.setText("");
        SocioPersistencia sp = new SocioPersistencia();
        cargarSocios(sp.obtenerTodos());
    }//GEN-LAST:event_btnCancelarBSocioActionPerformed

    private void btnCancelarBRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBRutaActionPerformed
        txtBuscarRuta.setText("");
        RutaNegocio rn = new RutaNegocio();
        cargarRutas(rn.verRutas());
    }//GEN-LAST:event_btnCancelarBRutaActionPerformed

    private void btnCancelarBPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBPrestamoActionPerformed
        txtBuscarPrestamo.setText("");
        PrestamoPersistencia pp = new PrestamoPersistencia();
        cargarPrestamos(pp.obtenerTodos());
    }//GEN-LAST:event_btnCancelarBPrestamoActionPerformed
    
    public void limpiarSocio() {
        txtRfcSocio.setText("");
        txtNombreSocio.setText("");
        socio = null;
    }
    
    public boolean verificarSocio() {
        return (!"".equals(txtNombreSocio.getText()) && !"".equals(txtRfcSocio.getText()));
    }
    
    public void cargarSocios(List<Socio> socios) {
        model = (DefaultTableModel) tbSocio.getModel();
        model.getDataVector().clear();
        String prestamo = "";
        for (Socio s : socios) {
            model.addRow(new Object[]{
                s.getId(),
                s.getNombre(),
                s.getRfc(),});
        }
    }
    
    public void cargarPrestamos(List<Prestamo> prestamos) {
        model = (DefaultTableModel) tbPrestamo.getModel();
        model.getDataVector().clear();
        String estado = "";
        if (prestamos.size() > 0) {
            for (Prestamo p : prestamos) {
                if (p.isEstado()) {
                    estado = "Actual";
                } else {
                    estado = "Pasado";
                }
                model.addRow(new Object[]{
                    p.getId(),
                    p.getSocio().getNombre(),
                    p.getFecha(),
                    p.getCantidad(),
                    p.getInteres(),
                    p.getDescuento(),
                    p.getPlazo(),
                    p.getResto(),
                    p.getTotal(),
                    estado
                });
            }
        } else {
            tbPrestamo.setVisible(false);
            tbPrestamo.setVisible(true);
        }
        
    }
    
    public static void cargarPeriodos(List<Periodo> periodos) {
        model = (DefaultTableModel) tbPeriodo.getModel();
        model.getDataVector().clear();
        if (periodos.size() > 0) {
            tbPeriodo.setVisible(true);
            for (Periodo p : periodos) {
                model.addRow(new Object[]{
                    p.getId(),
                    p.getFechaInicio(),
                    p.getFechaFin(),
                    p.getEstado()
                });
            }
        } else {
            tbPeriodo.setVisible(false);
            tbPeriodo.setVisible(true);
        }
        
    }
    
    public void cargarRutas(List<Ruta> rutas) {
        model = (DefaultTableModel) tbRuta.getModel();
        model.getDataVector().clear();
        for (Ruta r : rutas) {
            model.addRow(new Object[]{
                r.getId(),
                r.getNombre(),
                r.getDescripcion(),
                r.getKilometraje()
            });
        }
    }
    public static Socio socio = null;
    
    public void limpiarPrestamo() {
        btnSeleccionarSocioPrestamo.setText("Seleccionar");
        txtCantidadPrestamo.setText("");
        dcFechaPrestamo.setDate(null);
        cmbPlazoPrestamo.setSelectedIndex(0);
        txtInteresPrestamo.setText("");
        lbDescuentoPrestamo.setText("00.00");
        lbTotal.setText("00.00");
        lbSocio.setText("Socio");
    }
    
    public boolean verificarPrestamo() {
        return (socio != null && !"".equals(txtCantidadPrestamo.getText()) && dcFechaPrestamo.getDate() != null
                && cmbPlazoPrestamo.getSelectedIndex() != 0 && !"".equals(txtInteresPrestamo.getText())
                && !"00.00".equals(lbDescuentoPrestamo.getText()));
    }
    
    public boolean verificarRuta() {
        return (!"".equals(txtNombreRuta.getText()) && !"".equals(txtKilometraje.getText()) && !"".equals(txtDescripcion.getText()));
    }
    public static int indicador = -1;
    
    public void calcularDescuento() {
        DecimalFormat df = new DecimalFormat("00.00");
        double cantidad = Double.parseDouble(txtCantidadPrestamo.getText());
        double interes = Double.parseDouble(txtInteresPrestamo.getText());
        int plazo = cmbPlazoPrestamo.getSelectedIndex();
        double total = cantidad + (cantidad * (interes / 100));
        double descuento = total / (plazo * 52);
        lbTotal.setText(String.valueOf(df.format(total)));
        lbDescuentoPrestamo.setText(String.valueOf(df.format(descuento)));
    }
    
    public boolean verificarDescuento() {
        return (!"".equals(txtCantidadPrestamo.getText()) && cmbPlazoPrestamo.getSelectedIndex() != 0 && !"".equals(txtInteresPrestamo.getText()));
    }
    
    public boolean verificarPeriodo() {
        return (dcFechaInicioPeriodo.getDate() != null && dcFechaFinPeriodo.getDate() != null);
    }
    public static Periodo periodo = new Periodo();
    
    public void buscarRfc() {
        model = (DefaultTableModel) tbSocio.getModel();
        model.getDataVector().clear();
        List<Socio> socios = new ArrayList<>();
        SocioPersistencia sp = new SocioPersistencia();
        socios = sp.obtenerTodos();
        for (Socio s : socios) {
            if (s.getRfc().toLowerCase().startsWith(txtCriterioBusquedaSocio.getText().toLowerCase())) {
                model.addRow(new Object[]{
                    s.getId(), s.getNombre(), s.getRfc()
                });
            } else {
                tbSocio.setVisible(false);
            }
        }
        tbSocio.setVisible(true);
    }
    
    public void buscarNombre() {
        model = (DefaultTableModel) tbSocio.getModel();
        model.getDataVector().clear();
        List<Socio> socios = new ArrayList<>();
        SocioPersistencia sp = new SocioPersistencia();
        socios = sp.obtenerTodos();
        for (Socio s : socios) {
            if (s.getNombre().toLowerCase().matches(".*" + txtCriterioBusquedaSocio.getText().toLowerCase() + ".*")) {
                model.addRow(new Object[]{
                    s.getId(), s.getNombre(), s.getRfc()
                });
            } else {
                tbSocio.setVisible(false);
            }
        }
        tbSocio.setVisible(true);
    }
    
    public void buscarSocioPrestamo() {
        model = (DefaultTableModel) tbPrestamo.getModel();
        model.getDataVector().clear();
        List<Prestamo> prestamos = new ArrayList<>();
        PrestamoNegocio pn = new PrestamoNegocio();
        prestamos = pn.verPrestamos();
        for (Prestamo p : prestamos) {
            if (p.getSocio().getNombre().toLowerCase().matches(".*" + txtBuscarPrestamo.getText().toLowerCase() + ".*")) {
                model.addRow(new Object[]{
                    p.getId(),
                    p.getSocio().getNombre(),
                    p.getFecha(),
                    p.getCantidad(),
                    p.getInteres(),
                    p.getDescuento(),
                    p.getPlazo()
                });
            } else {
                tbPrestamo.setVisible(false);
            }
        }
        tbPrestamo.setVisible(true);
    }
    public static Ruta ruta;
    
    public void limpiarRuta() {
        txtNombreRuta.setText("");
        txtKilometraje.setText("");
        txtDescripcion.setText("");
        ruta = null;
    }
    
    public void soloLetras(char c, KeyEvent evt, JTextField txt) {
        if (!Character.isLetter(c) && !Character.isISOControl(c) && !Character.isSpace(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(txt, "Solo letras");
        }
    }
    
    public void soloNumeros(char c, KeyEvent evt, JTextField txt) {
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.') && !Character.isISOControl(c)) {
            JOptionPane.showMessageDialog(txt, "Solo puede ingresar números");
            evt.consume();
        }
        if (c == '.' && txt.getText().contains(".")) {
            evt.consume();
        }
    }
    
    public void buscarRuta() throws SQLException {
        model = (DefaultTableModel) tbRuta.getModel();
        model.getDataVector().clear();
        List<Ruta> rutas = new ArrayList<>();
        RutaNegocio rn = new RutaNegocio();
        rutas = rn.verRutas();
        for (Ruta r : rutas) {
            if (r.getNombre().toLowerCase().matches(".*" + txtBuscarRuta.getText().toLowerCase() + ".*")) {
                model.addRow(new Object[]{
                    r.getId(),
                    r.getNombre(),
                    r.getDescripcion(),
                    r.getKilometraje()
                });
            } else {
                tbRuta.setVisible(false);
            }
        }
        tbRuta.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPeriodo;
    private javax.swing.JButton btnAgregarRuta;
    private javax.swing.JButton btnCalcularDescuento;
    private javax.swing.JButton btnCancelarBPrestamo;
    private javax.swing.JButton btnCancelarBRuta;
    private javax.swing.JButton btnCancelarBSocio;
    private javax.swing.JButton btnCancelarPeriodo;
    private javax.swing.JButton btnCancelarPrestamo;
    private javax.swing.JButton btnCancelarRuta;
    private javax.swing.JButton btnCancelarSocio;
    private javax.swing.JButton btnCapturarPeriodo;
    private javax.swing.JButton btnCerrarSesionPeriodo;
    private javax.swing.JButton btnCerrarSesionPrestamo;
    private javax.swing.JButton btnCerrarSesionRuta;
    private javax.swing.JButton btnCerrarSesionSocio;
    private javax.swing.JButton btnEditarRuta;
    private javax.swing.JButton btnEditarSocio;
    private javax.swing.JButton btnGuardarPrestamo;
    private javax.swing.JButton btnGuardarSocio;
    public static javax.swing.JButton btnSeleccionarSocioPrestamo;
    private javax.swing.JButton btnVerPeriodo;
    private javax.swing.JButton btnVerPrestamo;
    private javax.swing.JButton btnVerSocio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbCriterioBusquedaSocio;
    private javax.swing.JComboBox cmbPlazoPrestamo;
    private com.toedter.calendar.JDateChooser dcFechaFinPeriodo;
    private com.toedter.calendar.JDateChooser dcFechaInicioPeriodo;
    private com.toedter.calendar.JDateChooser dcFechaPrestamo;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDescuentoPrestamo;
    public static javax.swing.JLabel lbSocio;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JRadioButton rbActualesPrestamos;
    private javax.swing.JRadioButton rbCapturadosReportes;
    private javax.swing.JRadioButton rbEspera;
    private javax.swing.JRadioButton rbPasadosPrestamos;
    private javax.swing.JRadioButton rbPendientesReportes;
    private javax.swing.JRadioButton rbTodosPeriodos;
    private javax.swing.JRadioButton rbTodosPrestamos;
    public static javax.swing.JTable tbPeriodo;
    private javax.swing.JTable tbPrestamo;
    private javax.swing.JTable tbRuta;
    private javax.swing.JTable tbSocio;
    private javax.swing.JTextField txtBuscarPrestamo;
    private javax.swing.JTextField txtBuscarRuta;
    private javax.swing.JTextField txtCantidadPrestamo;
    private javax.swing.JTextField txtCriterioBusquedaSocio;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtInteresPrestamo;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtNombreRuta;
    private javax.swing.JTextField txtNombreSocio;
    private javax.swing.JTextField txtRfcSocio;
    // End of variables declaration//GEN-END:variables
}
